# Generated by Django 2.1.3 on 2019-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='pre_content',
            field=models.TextField(default=1, verbose_name='编辑内容'),
            preserve_default=False,
        ),
    ]
