# Generated by Django 2.2.12 on 2020-06-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0021_projectreport_allow_pdf'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['top_doc', 'parent_doc', 'status'], name='app_doc_doc_top_doc_09d61d_idx'),
        ),
    ]
