# Generated by Django 2.2.12 on 2020-06-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0022_auto_20200618_2024'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['sort'], name='app_doc_doc_sort_0be3c7_idx'),
        ),
    ]
