# Generated by Django 2.2.12 on 2020-09-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0025_doc_editor_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='editor_mode',
            field=models.IntegerField(default=1, verbose_name='编辑器模式'),
        ),
    ]
