# Generated by Django 2.2.12 on 2020-11-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0028_docshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docshare',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
