# Generated by Django 2.2.12 on 2020-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0029_auto_20201101_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='docshare',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分享Token'),
        ),
        migrations.AlterField(
            model_name='docshare',
            name='effective_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
