# Generated by Django 2.2.12 on 2020-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0031_remove_docshare_effective_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='docshare',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
    ]
