# Generated by Django 2.2.12 on 2020-11-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0032_docshare_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='open_children',
            field=models.BooleanField(default=False, verbose_name='展开下级目录'),
        ),
    ]
