# Generated by Django 2.2.12 on 2020-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0033_doc_open_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='show_children',
            field=models.BooleanField(default=False, verbose_name='显示下级文档'),
        ),
    ]
