# Generated by Django 2.2.12 on 2020-12-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0034_doc_show_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文集图标'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文集名称'),
        ),
    ]
