# Generated by Django 2.2.12 on 2020-12-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0035_auto_20201221_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_watermark',
            field=models.BooleanField(default=False, verbose_name='水印状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='watermark_type',
            field=models.IntegerField(default=1, verbose_name='水印类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='watermark_value',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='水印内容'),
        ),
    ]
