# Generated by Django 2.2.12 on 2020-12-30 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_doc', '0036_auto_20201229_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_type', models.IntegerField(verbose_name='收藏类型')),
                ('collect_id', models.IntegerField(verbose_name='收藏对象ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '我的收藏',
                'verbose_name_plural': '我的收藏',
            },
        ),
    ]
