# Generated by Django 2.2.12 on 2021-01-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0037_mycollect'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
