# Generated by Django 4.2.16 on 2025-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0041_alter_attachment_id_alter_doc_id_alter_dochistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='index_position',
            field=models.IntegerField(default=0, verbose_name='首页链接位置'),
        ),
    ]
