# Generated by Django 4.2.16 on 2025-07-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_alter_emaiverificationcode_id_alter_registercode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercode',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='注册码有效期'),
        ),
    ]
